# backend/app/domain/entities/assumption.py
from dataclasses import dataclass, field
from datetime import datetime
from uuid import UUID, uuid4

from app.domain.value_objects.enums import AssumptionGroup, ForecastMethod, SourceType


@dataclass
class AssumptionSet:
    """
    A named collection of financial assumptions for a Deal.

    When evaluating a real estate deal, analysts create different scenarios
    (e.g., "Base Case", "Optimistic", "Conservative") with varying assumptions.
    Each scenario is an AssumptionSet containing multiple Assumption entries.

    A "Base Case" AssumptionSet is automatically created when a Deal is created.
    """

    deal_id: UUID
    name: str
    id: UUID = field(default_factory=uuid4)
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class Assumption:
    """
    A single financial assumption used in deal underwriting.

    Underwriting = the process of analyzing a deal's financials to decide
    whether to invest and at what price.

    Assumptions are key-value pairs like "cap_rate: 5.5%" or "rent_growth: 3%"
    that feed into financial models. Each assumption tracks:
    - Its numeric value and unit (e.g., 5.5, "%")
    - An optional range (min/max) for sensitivity analysis
    - Where it came from (source_type): extracted from the OM (Offering
      Memorandum), generated by AI, or manually entered

    Assumptions are AI-generated and displayed read-only to users.
    """

    set_id: UUID
    key: str
    id: UUID = field(default_factory=uuid4)
    value_number: float | None = None
    unit: str | None = None
    range_min: float | None = None
    range_max: float | None = None
    source_type: SourceType = SourceType.MANUAL
    source_ref: str | None = None
    notes: str | None = None
    group: AssumptionGroup | None = None
    forecast_method: ForecastMethod | None = None
    forecast_params: dict | None = None
    updated_at: datetime = field(default_factory=datetime.utcnow)
