"""add exploration chat and snapshot tables

Revision ID: 908ebab05098
Revises: 5a7867bf4f27
Create Date: 2026-03-07 15:47:25.771461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.infrastructure.persistence.models import UUIDType


# revision identifiers, used by Alembic.
revision: str = '908ebab05098'
down_revision: Union[str, Sequence[str], None] = '5a7867bf4f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exploration_sessions',
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('deal_id', UUIDType(length=36), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exploration_sessions_deal_id'), 'exploration_sessions', ['deal_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('deal_id', UUIDType(length=36), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('session_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_deal_id'), 'snapshots', ['deal_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('exploration_session_id', UUIDType(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('connectors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exploration_session_id'], ['exploration_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_exploration_session_id'), 'chat_sessions', ['exploration_session_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('session_id', UUIDType(length=36), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_exploration_session_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_snapshots_deal_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_exploration_sessions_deal_id'), table_name='exploration_sessions')
    op.drop_table('exploration_sessions')
    # ### end Alembic commands ###
