"""add tags and new tables

Revision ID: b611de5dff14
Revises: 908ebab05098
Create Date: 2026-03-09 18:13:22.366552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b611de5dff14'
down_revision: Union[str, Sequence[str], None] = '908ebab05098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('exploration_sessions', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exploration_sessions', 'tags')
    op.drop_column('deals', 'tags')
    # ### end Alembic commands ###
